spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8081/customers/
          predicates:
            - Path= /customers/**
        - id: r2
          uri: http://localhost:8082/products/
          predicates:
            - Path= /products/**

